listen ${HTTPS_PORT} ssl;
http2 on;
ssl_certificate ${TLS_CERT_FILE};
ssl_certificate_key ${TLS_KEY_FILE};
ssl_protocols ${TLS_PROTOCOLS};
ssl_session_cache shared:SSL:5m;
ssl_session_timeout 1h;
ssl_session_tickets off;
